### ISSUE TITLE
Isn`t it lossy? 

### ISSUE THREAD

**Issue by necros2k7** [Kroc/DOOM-Crusher#1]
%BIN_PNGCRUSH% -nobail -blacken -brute -keep grAb -keep alPh -l 9 -noforce -ow -reduce %FILE%  >NUL 2>&1
"-reduce"
Won`t it hurt visual experience?

**Comment by Kroc** [comment]
`-reduce` will only reduce the bit-depth if the existing image has the same number of colours. If you create a PNG containing 8 colours, but save it as a 32-bit PNG, `-reduce` will know that an 8-bit PNG will represent the same without colour loss. This is not the same as quantisation, which will actually remove colours to fit, e.g. nuQuant.

**Comment by Kroc** [comment]
The pngcrush source code has a comment explaining the option:

```
Version 1.7.49
  Implemented "-reduce" option to identify and reduce all-gray images,
  all-opaque images, unused PLTE entries, and 16-bit images that can
  be reduced losslessly to 8-bit.
```
