### ISSUE TITLE
Is it safe to optimize DOS era wads so it`s demos (lmp) can be played in DOS?

### ISSUE THREAD

**Issue by necros2k7** [Kroc/DOOM-Crusher#4]
subj

**Comment by Kroc** [comment]
PortaDOOM only strings together an existing set of tools that I didn't write myself but I know that the optimisations are designed to decrease file size and are very unlikely to make enough difference performance wise to be noticeable. Where optimisations that may theoretically improve speed (such as combining linedefs) exist, PortaDOOM does not use these as I've found them to be too destructive, breaking a large number of WADs and working only in a small, select number of cases (YMMV)

If you're trying to run more modern mods on a real MS-DOS machine, then a better DOS port is what you need. Try prBoom, largely considered to be the fastest DOS Doom.

**Comment by necros2k7** [comment]
I meant is it safe to use wads in DOS after Doom-crusher optimization?

**Comment by Kroc** [comment]
Ah okay, demos will be unaffected!
