### ISSUE TITLE
Feature Request: Linux version?

### ISSUE THREAD

**Issue by Shockwave508** [Kroc/DOOM-Crusher#6]
I tried running your program through Wine, but it's expecting operators and getting syntax errors left and right. Any chance of a native Linux version?

**Comment by Kroc** [comment]
I'm sorry, it's really just a bunch of programs clobbered together with a batch script and it wouldn't be possible to translate to Linux without rewriting from scratch as a real program which largely defeats the purpose of automating a set of separate utilities using a batch script. I don't think there's the demand given the higher skill level of Linux user. As an alternative you can use SLADE to compress PNG images inside PK3s/WADs although I wish there were an automated way to do this (LUA script maybe?).

I intend to migrate to Linux in the future, so who knows, but it may be years before I have the time to redo DOOM crusher all over again :)
